Repository Rafael-Morais-D/tn15-pi-grupo01, pull requests merged in 2020-06, with the labels that each got.

#3 Adicionando página de cadastro
  assets/css/style.css
  cadastro.php
  inc/footer.php
  inc/header.php
Labels: documentation

#4 Hotfix - Atribuindo o link do modal Termos de Uso na página de cadastro
  cadastro.php
Labels: documentation

#5 Header footer
  assets/css/style.css
  inc/footer.php
  inc/header.php
Labels: enhancement

#6 Acrescentando novos campos no formulário de cadastro
  cadastro.php
Labels: enhancement

#7 Ajustes no header e footer para melhor visualização mobile
  assets/css/style.css
  inc/footer.php
  inc/header.php
Labels: enhancement

#8 Adicionando página listagem de produtos
  admProdutos.php
Labels: enhancement

#9 Primeira versão da tabela de usuários do painel administrativo
  admUsuarios.php
Labels: enhancement

#11 Adicionando página cesta de compras
  cesta-de-compras.php
  inc/header.php
Labels: enhancement

#12 Adicionando Metatags para o SEO
  inc/head.php
Labels: enhancement

#13 Alterando e adicionando novas funções
  assets/css/style.css
  cesta-de-compras.php
  inc/head.php
  inc/header.php
  index.php
Labels: enhancement

#17 Atualização header-footer
  admCategoria.php
  admMensagem.php
  admProduto.php
  admUsuario.php
  assets/css/style.css
  cesta-de-compras.php
  inc/footer.php
  inc/header-adm.php
  inc/header.php
Labels: bug, enhancement

#18 Aplicando as alterações nas páginas
  assets/css/style.css
  cesta-de-compras.php
  inc/footer.php
  inc/head.php
Labels: bug

#19 Adicionando página de edição de usuário
  admEdicaoUsuario.php
  assets/css/style.css
  historicoPedidos.php
  inc/footer.php
  inc/header-adm.php
Labels: enhancement

#20 Pagamento
  cesta-de-compras.php
  inc/footer.php
  pagamento.php
Labels: enhancement

#24 Primeira versão - Página de contato
  assets/css/style.css
  contato.php
Labels: enhancement

#26 Hotfix - Alinhando botão de quantidade dos cards e deixando responsivo
  index.php
Labels: bug
